services:
  web:
    image: {{odooImage}}
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo      
    ports:
      - "{{odooPort}}:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    restart: always
    networks:
      - custom_network

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - custom_network


  sqlpad:
    image: sqlpad/sqlpad:latest
    ports:
      - "3000:3000"
    environment:
      - SQLPAD_ADMIN=admin@example.com
      - SQLPAD_ADMIN_PASSWORD=admin
    volumes:
      - sqlpad-data:/var/lib/sqlpad
    networks:
      - custom_network

volumes:
  odoo-web-data:
  odoo-db-data:
  sqlpad-data:

networks:
  custom_network:
    name: ${NETWORK_NAME:-odoo_network}
