
services:
  web:
    image: odoo:{{odooVersion}}
    depends_on:
      - db
    volumes:
      - ../:/mnt/extra-addons/{{moduleName}}
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_NAME=odoo
    networks:
      - custom_network
    restart: always
  db:
    image: postgres:{{postgresVersion}}
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - custom_network
    restart: always

volumes:
  odoo-data:
  postgres-data:
networks:
  custom_network:
    name: ${NETWORK_NAME:-odoo_network}